### ISSUE TITLE
TTS

### ISSUE THREAD

**Issue by yocontra** [bahamas10/node-celery-man#2]
Use "say" or another TTS engine to speak "engaged"

**Comment by yocontra** [comment]
This is a core component of the app - how dare you release this utility without it

**Comment by bahamas10** [comment]
excuse me paul, your wife is on the phone, it's an emergency.

**Comment by yocontra** [comment]
needs a push to npm

**Comment by bahamas10** [comment]
![hogie](http://media.steampowered.com/steamcommunity/public/images/avatars/00/0036af307254a94cb5edefd0b6f80b6646cf75fe_full.jpg)

help me hoagie man

```
$ npm show celery-man | grep version:
  version: '0.0.2',
```

**Comment by yocontra** [comment]
![](http://25.media.tumblr.com/tumblr_lt116mIA581r3a9fdo1_400.gif)

**Comment by yocontra** [comment]
say only works on macs

```
contra@ubuntu:~$ celery-man
4d3d3d3... engaged
execvp(): No such file or directory


events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: write EPIPE
    at errnoException (net.js:770:11)
    at Object.afterWrite (net.js:594:19)

```

**Comment by bahamas10** [comment]
that's lame as hell, i used a module so i thought it would be good. you got me friend.

**Comment by bahamas10** [comment]
543618a7fb790371b9b87c0adb9661e7cfe980f9 i dropped that module in favor of this... it only works on macs for now, but it doesn't break on other operating systems.

![](http://media.tumblr.com/tumblr_l1u47n4Qlg1qatf2v.gif)
